name: Build & Push Docker Images

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags for app image
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ptinkler/pollo-api
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Tags for nginx image
        id: meta-nginx
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ptinkler/pollo-nginx
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}

      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: nginx/Dockerfile
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}